# Generated by Django 5.1.4 on 2025-03-30 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0003_inventorycategory_supplyrequesttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplyrequesttable',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovate.inventorycategory'),
        ),
    ]
